
-- AI briefs: short personalized insights generated by the AI per scope per day
CREATE TABLE IF NOT EXISTS public.ai_briefs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  scope text NOT NULL CHECK (scope IN ('today','finance','plan','health')),
  headline text NOT NULL,
  body text NOT NULL,
  actions jsonb NOT NULL DEFAULT '[]'::jsonb,
  related_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.5,
  generated_for_date date NOT NULL DEFAULT CURRENT_DATE,
  dismissed_at timestamptz,
  model text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_briefs_user_scope_date
  ON public.ai_briefs (user_id, scope, generated_for_date DESC);

ALTER TABLE public.ai_briefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own ai_briefs" ON public.ai_briefs
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own ai_briefs" ON public.ai_briefs
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own ai_briefs" ON public.ai_briefs
  FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users delete own ai_briefs" ON public.ai_briefs
  FOR DELETE USING (auth.uid() = user_id);

-- AI clarifying questions ("learning loop")
CREATE TABLE IF NOT EXISTS public.ai_brief_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  brief_id uuid REFERENCES public.ai_briefs(id) ON DELETE CASCADE,
  question text NOT NULL,
  answer text,
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  asked_at timestamptz NOT NULL DEFAULT now(),
  answered_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_ai_brief_questions_user
  ON public.ai_brief_questions (user_id, asked_at DESC);

ALTER TABLE public.ai_brief_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own ai questions" ON public.ai_brief_questions
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own ai questions" ON public.ai_brief_questions
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own ai questions" ON public.ai_brief_questions
  FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users delete own ai questions" ON public.ai_brief_questions
  FOR DELETE USING (auth.uid() = user_id);
